name: Code formatting check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        deno-version: [1.4.4]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno fmt --check
